### ISSUE TITLE
Exercicio 1, aula 03

### ISSUE THREAD

**Issue by josuedevgit** [SkiereszDiego/Java-Caldeira#10]
Pessoal, no método de ``` verificarInformacoes() ``` fiquei meio travado e precisava de um help.

Tenho dúvida sobre o que esse método deve retornar. Deveria ser um Array o retorno dele? Mas nos meus testes vi que é meio complicado, porque a classe ``` ContaBancaria ``` tem vários tipos.

Se souberem de alguma forma, agredeceria a ajuda!

**Comment by IagoCappeletti** [comment]
Olá,

acho que para resolver o questão dos diversos tipos, tu pode definir todos como String e quando for usar a variável tu pode converter com o metodo Integer. parseInt()
(Ele converte uma string em um número inteiro.)

**Comment by josuedevgit** [comment]
Perfeito, mano! Fiz as conversões que precisava e consegui retornar o array! Valeu!!
