### ISSUE TITLE
A "charada" do exercicio 3 da aula 4. Minha percepção.

### ISSUE THREAD

**Issue by vaguinhu** [SkiereszDiego/Java-Caldeira#11]
###

Após fazer o código, eu não consegui perceber a "charada", eu enxerguei exercício como um desafio. 

Deixa eu explicar melhor a minha visão.

Bom, devemos criar uma estrutura de classes que seja flexível o suficiente para acomodar diferentes tipos de bens financeiros, cada um com sua própria lógica de cálculo de tributos. Ao mesmo tempo, precisamos garantir que apenas objetos tributáveis possam ser adicionados ao gerenciador de imposto de renda. Certo?

Pra mim a "charada" neste exercício é criar um programa de computador que calcula impostos para diferentes tipos de coisas financeiras, como contas bancárias e seguros. A charada é fazer isso de uma forma que:

- Cada tipo de coisa financeira saiba como calcular seus próprios impostos.

- Você pode adicionar mais tipos de coisas financeiras no futuro sem muita complicação.

Para resolver essa charada, você precisa usar conceitos de programação que permitem isso, como herança (fazer coisas parecidas compartilharem código), interfaces (definir regras comuns para diferentes coisas) e polimorfismo (fazer objetos diferentes agirem de maneira similar).

Mas se forem notar, o exercício pede **interface**, algo que não está na documentação da aula 4, não tem exemplos, então vai da gente ir atrás e pesquisar o que é interface. O desafio esta em descobri qual interface usar. Devemos utilizar uma interface Tributavel.

Mas caso, quiserem oque é interface em java, vou deixar minha explicação.

**O que é interface?**

Em Java, uma interface é como um conjunto de regras que você diz para outras classes seguir. Imagine que você está jogando um jogo de quebra-cabeça e cada peça tem que se encaixar em um lugar específico. A interface é como a forma desse lugar onde as peças devem se encaixar.

Na interface, você diz quais ações (métodos) uma classe deve fazer, mas você não diz como a classe deve fazer essas ações. Por exemplo, você pode ter uma interface chamada **Movel** que diz que qualquer objeto que a implemente deve ter um método chamado **mover()**. No entanto, como um objeto se move (andar, voar, etc.) é com cada classe que implementa essa interface.

Assim, a interface é como um contrato que obriga outras classes a fornecerem certas funcionalidades, mas permite que elas escolham como fazer isso. É uma maneira de garantir que diferentes objetos possam ser usados de maneira semelhante em seu código, mesmo que sejam de tipos diferentes.

> Exemplos de interface:
> 
> Declaração de Interface: Para criar uma interface, você usa a palavra-chave **interface**. 
> 
> `
> public interface Tributavel {
>     double calculaTributos();
> }
> `
> 
> 1. Métodos Abstratos: Em uma interface, todos os métodos são implicitamente abstratos, o que significa que eles não têm implementação. No exemplo acima, **calculaTributos()** é um método abstrato.
> 2. Implementação em Classes Concretas: As classes que implementam uma interface devem fornecer uma implementação real para todos os métodos da interface. Por exemplo:
> 
> 
> `
> public class ContaCorrente implements Tributavel {
>     @Override
>     public double calculaTributos() {
>         // Implementação específica para ContaCorrente
>         return saldo * 0.01;
>     }
> }
> `
> 
> 1. Múltiplas Interfaces: Uma classe em Java pode implementar várias interfaces. Isso permite que você adicione funcionalidades de várias fontes diferentes a uma classe.
> 2. Contrato: As interfaces são usadas para estabelecer um contrato entre classes. Isso garante que as classes que implementam a interface ofereçam os métodos especificados na interface.
> 3. Polimorfismo: O uso de interfaces permite o polimorfismo, onde você pode tratar objetos de diferentes classes que implementam a mesma interface de forma semelhante.

**RESUMO**

Resumindo, não é bem, uma charada, e sim um desafio, que é criar um programa de impostos que seja flexível e possa lidar com diferentes coisas financeiras, cada uma calculando seus impostos de maneira única. Ou seja, criar uma interface que será responsável por definir um contrato (conjunto de métodos) que todas as classes que representam objetos tributáveis devem implementar. No contexto do exercício, a interface Tributavel deve conter o método **calculaTributos()**, que será usado para calcular os tributos associados a cada objeto tributável.

Aqui está como você pode definir a interface Tributavel no exercício:

`public interface Tributavel {
    double calculaTributos();
}
`
Em seguida, todas as classes que representam objetos tributáveis, como **ContaCorrente** e **SeguroDeVida**, devem implementar essa interface e fornecer sua própria implementação do método **calculaTributos()** de acordo com as regras específicas para cada tipo de objeto. Isso garante que todas essas classes tenham um método **calculaTributos()** em comum, permitindo que você as trate de maneira semelhante no gerenciamento de impostos.

Bom, é a minha percepção sobre a charada, se você tiver uma opinião diferente, por favor, fique a vontade para debatermos sobre o exercício.

**Comment by mbritzke** [comment]
Perfeita explicação!
Poderia, inclusive, adicionar essa explicação dentro do nosso repositório, via fork e pull request @vaguinhu
