### ISSUE TITLE
Aula 04 exercício das formas geométricas

### ISSUE THREAD

**Issue by MarquinCss** [SkiereszDiego/Java-Caldeira#12]
é valido fazer um método de ` getNome( ) ` para falar o nome das formas?
EDIT:
![image](https://github.com/SkiereszDiego/Java-Caldeira/assets/115740827/c7101cd0-3b6a-41cf-8bab-ad3d971e92f5)
(Espero que não tenha problema, pq ficou muito fofinho.

**Comment by mbritzke** [comment]
Não tem problema Marco, pode deixar assim mesmo!
