### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by gabjohann** [SkiereszDiego/Java-Caldeira#15]
Os arquivos com extensão .iml e pertencentes ao diretório .ideia devem estar presente no repositório ou posso adicioná-los ao .gitignore?

**Comment by vitozs** [comment]
Achei um artigo que acho que pode ajudar, ele fala o seguinte:

"_Se você acidentalmente excluir o arquivo IML de um módulo, muitas vezes você pode regenerar o arquivo abrindo e fechando seu IDE, reconstruindo seu projeto ou reimportando seu projeto._"

Então acho que pode colocar no .gitignore, se tu achar que precisa. 

Link falando sobre a extensao: https://ficheiros.com.br/extensao/iml/

**Comment by mbritzke** [comment]
Concordo com o Vitor nessa, 
Mas já vi em vários repositórios no github que a pasta .idea do IntelliJ está lá e acredito que isso acontece por 2 motivos:

1. Otimiza a importação do IntelliJ;
2. O autor fez merda quando foi criar o .gitignore;

Pode deixar ela lá, o mais importante é ignorar os arquivos compilados ou arquivos de log. 
Mas se quiser fazer um "super" gitignore, recomendo esse site: 
https://www.toptal.com/developers/gitignore

**Comment by gabjohann** [comment]
Entendi, valeu!
