### ISSUE TITLE
Aula-08 / pom.xml

### ISSUE THREAD

**Issue by vitozs** [SkiereszDiego/Java-Caldeira#20]
### Screenshot do projeto
https://snipboard.io/NvFpzY.jpg

> By default, the Surefire Plugin will automatically include all the test classes with the following wildcard patterns:
> 
> “**/Test*.java” – includes all of its subdirectories and all Java filenames that start with “Test”
> “**/*Test.java” – includes all of its subdirectories and all Java filenames that end with “Test”
> “**/*Tests.java” – includes all of its subdirectories and all Java filenames that end with “Tests”
> “**/*TestCase.java” – includes all of its subdirectories and all Java filenames that end with “TestCase”
> So, if our tests don’t follow the above wildcard patterns, Maven isn’t going to pick these tests to run. However, there are cases where there could be project-specific naming patterns to be followed instead of these standard conventions. In those cases, we can override the Surefire Plugin by explicitly specifying the tests that we want to include (or exclude) and other patterns.

Link falando mais sobre: https://www.baeldung.com/maven-cant-find-junit-tests

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.mkyong.core</groupId>
    <artifactId>junit5-maven</artifactId>
    <version>1.0</version>

    <properties>
        <java.version>1.8</java.version>
        <junit-jupiter.version>5.5.2</junit-jupiter.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>

        <!-- junit 5 -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit-jupiter.version}</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>

            <!-- Need at least 2.22.0 to support JUnit 5 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M3</version>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>

        </plugins>
    </build>

</project>
```

**Comment by mbritzke** [comment]
Top! Adiciona isso no material via Fork -> Pull Request!
