### ISSUE TITLE
Duvida sobre Scrum Trello

### ISSUE THREAD

**Issue by IagoCappeletti** [SkiereszDiego/Java-Caldeira#25]
Boa noite! 

Fiquei com um duvida referente ao templete do trello. De qual modelo devo usar. 

![image](https://github.com/SkiereszDiego/Java-Caldeira/assets/113685735/95e3de7a-f85a-491e-b82c-9a0ddc568524)

![image](https://github.com/SkiereszDiego/Java-Caldeira/assets/113685735/402e37f8-eb0a-4a32-8325-0ba067c7b51e)

**Comment by mbritzke** [comment]
Fala Iago!

Boa pergunta, eu debati com o @SkiereszDiego e chegamos a 2 opções para ti:

1. Pegar o primeiro template e ter um cuidado com a segunda coluna, talvez renomear para "issues" - para trazer as duvidas para cá ou;
2. Criar um proprio de vocês com as colunas: Backlog, Backlog da Sprint (A Fazer) , Em andamento, revisão, Teste, Concluido - Para esse vocês podem esquematizar duas sprints de 3 dias cada.
