### ISSUE TITLE
.CSV do projeto revisão

### ISSUE THREAD

**Issue by eduardofettermann** [SkiereszDiego/Java-Caldeira#26]
Ficamos com dúvida sobre o arquivo .CSV que aparentemente há algumas "brechas" em algumas cidades

![image](https://github.com/SkiereszDiego/Java-Caldeira/assets/127540887/a9116b21-7f89-4961-9238-40cf812ddd65)

Foi proposital ou ta errado o arquivo?

**Comment by kvargazs** [comment]
Oii Fettermann, fiz um pull request disso, atualizei o arquivo, você está certo, tinham várias cidades com esse problema, só esperar os profs fecharem lá.

**Comment by mbritzke** [comment]
Pessoal, peço desculpas porque acabei subindo o arquivo errado antes, já atualizei - por favor trabalhem com o arquivo que está disponível agora!
