### ISSUE TITLE
Classe nao reconhecida no intellij

### ISSUE THREAD

**Issue by Kretzmann01** [SkiereszDiego/Java-Caldeira#29]
![image](https://github.com/SkiereszDiego/Java-Caldeira/assets/139182369/442400f3-864d-40b4-bf2b-ac86205ddbad)

estou tendo problemas no intellij, os arquivos não estão sendo reconhecidos como classes, assim não consigo rodar o projeto.

como posso resolver esse erro ?

**Comment by bian-ka** [comment]
Opa Gabriel! Tudo bem? 
![Capturar](https://github.com/SkiereszDiego/Java-Caldeira/assets/128072715/86a867d1-08b1-4fab-ab9d-1f0ef8730b87)

Tirei um print da minha tela pra te ajudar. Só ir ali no gradle, clicar no sinal de "+" e abrir o arquivo. O meu não está com as xicrinhas pois estou pelo windows. Abraços!

**Comment by Kretzmann01** [comment]
valeu pela força mas ja esta registrado o projeto no gradle

**Comment by mbritzke** [comment]
@Kretzmann01 já tentou esse passo a passo?
https://stackoverflow.com/questions/66543244/cause-zip-end-header-not-found

**Comment by Kretzmann01** [comment]
consegui resolver um pouco antes de ter respondido matheus, mas obrigado assim mesmo.
tive que fazer o download de uma pasta gradle com alguns arquivos e colar ela dentro de uma outra pasta com os dominios de gradle.
