### ISSUE TITLE
Aula 01 exercicio 5

### ISSUE THREAD

**Issue by MarquinCss** [SkiereszDiego/Java-Caldeira#3]
Estou tendo um pouco de dificuldade sobre como desenvolver esse exercicio. (08/09/23)
Exercicio 05
Crie um programa que armazene um horário (hora, minuto e segundo) em variáveis, depois, determine e exiba a quantidade de segundos que se passaram desde as 0h00min0s e a quantidade de segundos que faltam para a meia-noite.
Exercicio 06

**Comment by mbritzke** [comment]
Buenas Marquin! Tudo certo?
Sem problemas, poderia explicar melhor as tuas dúvidas com esse exercício?
Por exemplo: manipular os segundos dentro do programa ou não entendeu bem a proposta do exercício ou qualquer outra coisa kkkkkkk. 
Manda aí que a gente te ajuda!

**Comment by MarquinCss** [comment]
isso, como eu posso manipular os segundos, teria algum exemplo para me mostrar? grato <3

**Comment by mbritzke** [comment]
Utilizar o horário dinâmico seria uma das implementações possíveis, mas vamos focar numa solução mais simples primeiro:
Você pode receber um horário digitado pelo usuário, pedindo para ele inserir a hora, os minutos e segundos.
Com esses valores salvos em variáveis você parte para a parte do cálculo, para definir as duas quantidades de segundos que o exercício pede.
No momento que for realizar os cálculos, passe todos os valores para segundos, ou seja, você precisa descobrir quantos segundos tem numa hora, no minuto e no dia inteiro.

**Comment by MarquinCss** [comment]
Parece que ficou um pouco mais claro, vou usar como base, não tinha entendido que poderíamos usar essa parte de o usuário digitar e tals. Muito obrigado prof @mbritzke ♡.
