### ISSUE TITLE
Duvida dados estatísticos

### ISSUE THREAD

**Issue by bian-ka** [SkiereszDiego/Java-Caldeira#31]
Olá!! Estou com duvida em relação aos dados estatisticos.
- É custo total do transporte pelo numero de tipos de produtos ou custo total do transporte pelo numero total de produtos? 
Exemplo do cenario1: 
custo total / quantidade tipos de produtos: 29.794,31 / 4 
ou custo total / quantidade de produtos: 29.794,31 / (300+50+70+2000) 

- O custo por trecho é o mesmo que o custo total por trecho?

Dados estatísticos 📊💡
O programa deverá exibir um relatório dos transportes até então cadastrados: custo total, **o custo por trecho**, o custo médio por km, **o custo médio por tipo de produto**, **o custo total por trecho**, o custo total para cada modalidade de transporte, o número total de veículos deslocados e o total de itens transportados.

**Comment by mbritzke** [comment]
Oi Bianca,

Para a tuas dúvidas você precisa pensar em todos os transportes cadastrados, então se você tiver 2 transportes cada um vai ter um custo por trecho e juntando eles você vai ter o custo total daquele trecho.
