### ISSUE TITLE
Problema na Package IntelliJ

### ISSUE THREAD

**Issue by anitaeverywhere** [SkiereszDiego/Java-Caldeira#32]
## Problema nos arquivos source no IntelliJ

- Os arquivos da pasta source estão dando erro na máquina de quem clona o repositório

![image](https://github.com/SkiereszDiego/Java-Caldeira/assets/136662995/5b602745-28f3-4c64-abd0-6fe56af4383d)

![image](https://github.com/SkiereszDiego/Java-Caldeira/assets/136662995/0f28e0c4-8f6c-4824-819c-a8f688b0a85e)

**Comment by mbritzke** [comment]
Oi Anita, pode nos trazer mais informações? Só pelo print ficou muito genérico.

Teria alguma mensagem de erro?
