### ISSUE TITLE
Imagem de aula 05 não carrega

### ISSUE THREAD

**Issue by Davi-Ksk** [SkiereszDiego/Java-Caldeira#33]
Estava tentando revisar matrizes mas a imagem não carrega, era um exemplo que eu precisava bastante.

![imagem_2023-10-13_114816023](https://github.com/SkiereszDiego/Java-Caldeira/assets/51761519/d675875c-b6b0-4f6e-9f11-8a9f25daa3ae)

**Comment by mbritzke** [comment]
Imagem corrigida!
