### ISSUE TITLE
Aula da plataforma

### ISSUE THREAD

**Issue by MarquinCss** [SkiereszDiego/Java-Caldeira#37]
Ainda não recebi o acesso a plataforma que o Jean mandou o forms, é normal isso? alguém já conseguiu?

**Comment by GREGORY-MACHADO** [comment]
sor eu não consigo acesso no teams eu vou entrar e da erro

**Comment by MarquinCss** [comment]
@mbritzke @SkiereszDiego

**Comment by mbritzke** [comment]
Oi @MarquinCss , estava verificando aqui e seu email está cadastrado na plataforma.
Mas vamos fazer o seguinte, eu vou te adicionar novamente e tu testa novamente.

Oi @GREGORY-MACHADO , instala novamente o teu teams que vai solucionar o problema!
