### ISSUE TITLE
Projeto-Final 

### ISSUE THREAD

**Issue by vitozs** [SkiereszDiego/Java-Caldeira#38]
Boa noite, nós da equipe 10 gostaríamos de saber qual seria a finalidade da plataforma a ser desenvolvida nesse projeto. Ficamos em dúvida em relação a alguns tópicos:

- O que seria a interação entre os usuários da plataforma?
- Qual seria a relação entre o usuário e a API Zelda? Seria apenas consulta?
- Qual seria a finalidade da criação de uma API para consultar a API Zelda? Não fica redundante? Ou teremos que fazer alguma tratativa desses dados.

Obrigado!

**Comment by mbritzke** [comment]
Oi Vitor, claro! Vou responder todas as perguntas juntas, beleza?

A ideia em si dessa aplicação é criar uma plataforma que una as pessoas que gostam da franquia Zelda. 
Vocês vão notar ou já notaram que o sistema está dividido em 4 entregas pois queremos que vocês compreendam todas as etapas da entrega de um produto novo numa empresa. 
Mas aí que vem o plot twist, para vocês atenderem o objetivo do sistema em si, vocês precisam chegar na V3 que fará a relação de 1 usuário com seus jogos favortios da franquia.
Dito tudo isso, o sistema está dividido em 3 microserviços - para que vocês entedam um padrão de projeto - e o objetivo de criar um serviço que consuma uma API externa é que **_somente_** ele ficará responsável de lidar com tudo que a API externa faça (consulta aos jogos), minimizando os impactos no sistema como um todo além de ter o controle no teu ambiente.
Se vocês chegarem no cache, por exemplo, vão reparar que não vai precisar consultar o Zelda API, ou seja, quaisquer erros que ela tiver não vai impactar vocês já que os dados estaram no dominio de vocês.
Imagine o cenário real, a Zelda API está com erro ou ficou indisponivel, na manipulação dos containers, vocês poderiam desligar o serviço que consome ele antes que impacte todo o sistema.

Sacou a ideia?

**Comment by mbritzke** [comment]
E sim, vocês vão precisar fazer uma trativa nesses dados kkkk

**Comment by vitozs** [comment]
Tranquilo sor! Obrigado pelo retorno, acabou esclarecendo nossas duvidas
