### ISSUE TITLE
Não entendi uma parte exercício

### ISSUE THREAD

**Issue by josuedevgit** [SkiereszDiego/Java-Caldeira#4]
# Exercício 04, Aula 02

"###"

# Detalhes
No texto do exercício diz: "...Durante a execução o programa deve perguntar ao usuário se ele deseja continuar, se ele não quiser, deve digitar ‘n’ para o programa encerrar."

Minha dúvida é se, o programa deve mostrar a opção de encerrar **depois do resultado da operação**, ou antes?

**Comment by mbritzke** [comment]
Oi Josué, 
Pode mostrar a opção depois do resultado da operação que vai facilitar a organização do código.

**Comment by josuedevgit** [comment]
Thanks, guys!
