### ISSUE TITLE
Exercicio 4

### ISSUE THREAD

**Issue by josuedevgit** [SkiereszDiego/Java-Caldeira#5]
# Exercicio 4, aula 2

## Problema
Pessoal, construí uma lógica pra calculadora, mas quando vou fazer a verificação se o usuario quer continuar, o programa não inicia novamente, não respeitando o loop que criei, ou seja, ele encerra o programa. Fiz um teste em JavaScript (linguagem que estou mais habituado) e a lógica funcionou.

Segue meu código em Java:

``` 
public static void main(String[] args) {
        String loop = "s";
        while(loop == "s") {
            int numero1, numero2;

            Scanner sc = new Scanner(System.in);
            System.out.println("Vamos calcular!");
            System.out.println("Escolha uma operação para aplicar [*, /, +, -]:");
            String operacao = sc.nextLine();

            System.out.println("Digite o primeiro numero:");
            numero1 = sc.nextInt();

            System.out.println("Digite outro numero:");
            numero2 = sc.nextInt();

            switch(operacao) {
                case "*":
                    int multiplicacao = numero1 * numero2;
                    System.out.println(numero1 + " * " + numero2 + " = " + multiplicacao);
                    break;
                case "/":
                    int divisao = numero1 / numero2;
                    System.out.println(numero1 + " / " + numero2 + " = " + divisao);
                    break;
                case "+":
                    int adicao = numero1 + numero2;
                    System.out.println(numero1 + " + " + numero2 + " = " + adicao);
                    break;
                case "-":
                    int subtracao = numero1 - numero2;
                    System.out.println(numero1 + " - " + numero2 + " = " + subtracao);
                    break;
                default:
                    System.out.println("Dado inválido! Digite novamente! [*, /, +, -]");
                    break;
            }
            System.out.println("Você deseja calcular novamente [s == sim, n == nao]:");
            loop = sc.nextLine();
        }
    }
```

Sabem se tem uma particularidade do Java que faz fechar? Ou tem algo que não observei aí?
Quem puder contribuir, agradeço!

**Comment by moises-briceno** [comment]
Eai Josué, para comparar o valor ou conteúdo de duas String e saber se são iguais no Java se usa ".equals" no teu caso seria assim "while (loop.equals("s")) {}". 

O "==" tu usa se quiser saber se as duas variáveis de referência apontam para o mesmo objeto na memória que não seria o caso, já que queremos comparar o valor dentro delas

e também pode ser que o método "nextInt()" não consome a quebra de linha então o  usuário não vai conseguir digitar no próximo "nextLine()" porque tem uma quebra de linha pendente que o "nextLine()" consome.

para resolver o jeito que eu conheço é tipo colocar um "nextLine()" após ter colocado o "nextInt()" que dai eles vão consumir a quebra de linha que o "nextInt()" deixa pendente.

ficaria assim:
            System.out.println("Digite o primeiro numero:");
            numero1 = sc.nextInt();
            sc.nextLine();

            System.out.println("Digite outro numero:");
            numero2 = sc.nextInt();
            sc.nextLine();
 
Espero ter ajudado e não ter falado nenhuma besteira kkkk, qualquer coisa os professores me corrigem kkkkk

**Comment by moises-briceno** [comment]
também poderias usar o 
do {           
       }while ()
que no caso foi o que eu usei kkk

**Comment by josuedevgit** [comment]
Cara, ajudou muito! Era isso mesmo, valeu!!
