### ISSUE TITLE
dúvida sobre imagem - exercício 7

### ISSUE THREAD

**Issue by MarquinCss** [SkiereszDiego/Java-Caldeira#6]
-----------------------
O que era para ser a imagem que não carregou do exercício 7? era algo importante para a conclusão da atividade? 
----------------------------

**Comment by mbritzke** [comment]
Era para ser o Leonidas falando um "pouco mais" com base na piada do Thiago Ventura kkkkk.
Como não deu certo, segue o video da piada dele com o filme 300:
https://www.youtube.com/watch?v=JBFRkJUAjyQ

**Comment by MarquinCss** [comment]
Aí, que tudo! pena q não foi

**Comment by MarquinCss** [comment]
-Fechando Issue
