### ISSUE TITLE
pix

### ISSUE THREAD

**Issue by josuedevgit** [SkiereszDiego/Java-Caldeira#8]
### Pergunta
Na criação do método pix, a instrução está assim: ``` pix(double valor) ```
Mas pra quem que vamos tranferir? Colocamos um parâmetro de conta bancaria também?
Ou criamos um atributo de "chave pix"?

**Comment by mbritzke** [comment]
Pode adicionar o parâmetro da conta bancaria, o enunciado do exercicio é só uma base para vocês codificarem as soluções, não necessariamente precisa ser regras talhadas em pedras kkkkkk.

**Comment by josuedevgit** [comment]
Tá, valeu! kkkkk
